Repository cli-table/cli-table3, pull requests merged in 2018-06, with the labels that each got.

#2 Update Node version requirements
  .travis.yml
  package.json
Labels: breaking

#3 Add `yarn.lock` file
  yarn.lock
Labels: internal

#9 Use Jest for testing
  .travis.yml
  README.md
  gulpfile.js
  lib/print-example.js
  package.json
  test/cell-test.js
  test/layout-manager-test.js
  test/original-cli-table-index-tests.js
  test/original-cli-table-newlines-test.js
  test/table-layout-test.js
  test/table-test.js
  test/utils-test.js
  test/verify-legacy-compatibility-test.js
  yarn.lock
Labels: internal

#10 chore: use yarn cache
  .travis.yml
Labels: internal

#11 Update Documentation
  README.md
  advanced-usage.md
  basic-usage.md
Labels: documentation

#12 Add ESLint and Prettier
  .eslintrc.js
  examples/basic-usage-examples.js
  examples/col-and-row-span-examples.js
  lib/print-example.js
  package.json
  src/cell.js
  src/layout-manager.js
  src/table.js
  src/utils.js
  test/cell-test.js
  test/example-tests.js
  test/layout-manager-test.js
  test/original-cli-table-index-tests.js
  test/original-cli-table-newlines-test.js
  test/table-layout-test.js
  test/table-test.js
  test/utils-test.js
  test/verify-legacy-compatibility-test.js
  yarn.lock
Labels: internal

#15 Remove Gulp
  README.md
  gulpfile.js
  lib/print-example.js
  package.json
  scripts/print-examples.js
  scripts/update-docs.js
  yarn.lock
Labels: internal

#16 Replace `kind-of` dependency with `typeof` and `Array.isArray()`
  package.json
  src/cell.js
  src/layout-manager.js
  test/table-layout-test.js
Labels: internal

#21 Import type definition from `@types/cli-table2`
  index.d.ts
  package.json
Labels: enhancement
