Repository cli-table/cli-table3, pull requests merged in 2020-03, with the labels that each got.

#135 docs: use https
  README.md
Labels: documentation

#134 ci: fix eslint errors
  src/utils.js
  test/table-layout-test.js
Labels: internal

#156 Drop support for Node 6 and 8
  .travis.yml
  package.json
Labels: breaking

#132 Update lockfile
  yarn.lock
Labels: internal
